package com.snelnieuws.model

/** Backend-driven UI translations for the iOS + Android clients.
  *
  * Same shape as [[CategoryNames]] — a `Map[locale, Map[key, value]]`
  * with the English row as the source of truth and authoritative
  * fallback for unknown locales. Apps call `GET /v3/i18n?language=xx`
  * once on startup and on every language switch, cache the response,
  * and look up strings via `L10n.t("key")` instead of literal text.
  *
  * Adding a new language tomorrow:
  *   1. Add a new entry under `strings` for the locale code
  *   2. Make sure `Languages.codes` includes it (so the picker shows it)
  *   3. Deploy. Apps pick it up on next launch — no app release needed.
  *
  * Adding a new key:
  *   1. Add it under the "en" row (the source of truth)
  *   2. Add it under every other locale row, or leave it out and the
  *      English value is used as fallback at lookup time
  *   3. Mirror the same key in the apps' bundled fallback resources
  *      (`Localizable.strings` on iOS, `strings.xml` on Android) so
  *      offline / cache-cold launches still render usable text
  *
  * The `forLocale(locale)` resolver returns the inner map for the
  * requested locale, falling back to the English row for unknown
  * locales — same semantics as `CategoryNames.forLocale`.
  *
  * Per-locale Maps below are kept under ~200 keys (UI chrome only). If
  * we ever want copy-A/B testing or non-engineer-editable translations,
  * migrate to a DB-backed schema at that point — but the current scale
  * (~7 languages × ~150 keys) fits comfortably in process memory.
  */
object UiStrings {

  /** English source of truth. Every key must exist here. Other locale
    * rows may omit keys; the resolver falls back through `en` at
    * lookup time on the client.
    */
  private val en: Map[String, String] = Map(
    // ── Common UI ─────────────────────────────────────────────────
    "common.continue"               -> "Continue",
    "common.cancel"                 -> "Cancel",
    "common.skip"                   -> "Skip",
    "common.retry"                  -> "Retry",
    "common.save"                   -> "Save",
    "common.edit"                   -> "Edit",
    "common.delete"                 -> "Delete",
    "common.ok"                     -> "OK",
    "common.close"                  -> "Close",

    // ── Splash / app shell ─────────────────────────────────────────
    "app.name"                      -> "Snel Nieuws",

    // ── Force update ───────────────────────────────────────────────
    "forceUpdate.title"             -> "Update Required",
    "forceUpdate.message"           -> "A newer version of Snel Nieuws is available. Please update to continue.",
    "forceUpdate.cta"               -> "Update Now",

    // ── Login screen ───────────────────────────────────────────────
    "login.greeting"                -> "Hey,\nwelcome to",
    "login.email.title"             -> "Email Address",
    "login.email.placeholder"       -> "xyz@gmail.com",
    "login.password.title"          -> "Password",
    "login.password.placeholder"    -> "*****",
    "login.forgotPassword"          -> "Forgot password?",
    "login.signUp"                  -> "SIGN UP",
    "login.login"                   -> "LOGIN",
    "login.haveAccount"             -> "Already have an account?",
    "login.noAccount"               -> "Don't have an account?",
    "login.signUpCta"               -> "Sign up",
    "login.loginCta"                -> "Login",
    "login.or"                      -> "OR",
    "login.google.cta"              -> "Continue with Google",
    "login.privacy"                 -> "By continuing, you agree to our [Privacy Policy](https://api.snel.emudoi.com/privacy).",

    // ── Onboarding: language ───────────────────────────────────────
    "onboarding.lang.title"         -> "Pick your language",
    "onboarding.lang.subtitle"      -> "We'll show news in this language. You can change it anytime in Settings.",
    "onboarding.lang.error"         -> "Couldn't load languages — please retry.",

    // ── Onboarding: notification ───────────────────────────────────
    "onboarding.notif.title"        -> "Stay in the loop",
    "onboarding.notif.subtitle"     -> "How many news updates would you like to receive each day?",

    // ── Onboarding: category + inline custom feed ──────────────────
    "onboarding.cat.title"          -> "Pick your topics",
    "onboarding.cat.subtitle"       -> "Choose the categories you want to see in your feed. You can change this anytime from the menu.",
    "onboarding.cat.error"          -> "Couldn't load categories — please retry.",
    "onboarding.cat.customFeed.title"      -> "Custom feed (optional)",
    "onboarding.cat.customFeed.subtitle"   -> "Describe the kind of news you want to see and we'll match articles to it.",
    "onboarding.cat.customFeed.placeholder"-> "e.g. Dutch housing market",

    // ── Settings ───────────────────────────────────────────────────
    "settings.title"                -> "Settings",
    "settings.section.notifications"-> "NOTIFICATIONS",
    "settings.section.categories"   -> "CATEGORIES",
    "settings.section.country"      -> "COUNTRY",
    "settings.section.account"      -> "ACCOUNT",
    "settings.section.language"     -> "LANGUAGE",
    "settings.section.customFeed"   -> "MY CUSTOM FEED",

    "settings.language.label"       -> "Language",
    "settings.country.label"        -> "Country",
    "settings.notifications.updatesPerDay"        -> "How many updates per day",
    "settings.notifications.disabled.title"       -> "Notifications are disabled",
    "settings.notifications.disabled.subtitle"    -> "Tap to open system Settings",
    "settings.customFeed.setLabel"  -> "Set a custom query",
    "settings.customFeed.savedLabel"-> "Your custom query",
    "settings.customFeed.tapToDescribe" -> "Tap to describe your feed",

    "settings.account.logout"               -> "Logout",
    "settings.account.privacyPolicy"        -> "Privacy Policy",
    "settings.account.deleteAccount"        -> "Delete Account",
    "settings.account.deleteConfirm.title"  -> "Delete your account?",
    "settings.account.deleteConfirm.message"-> "This permanently removes your account, saved articles, and any data we hold about you. This cannot be undone.",

    // ── Language picker (Settings sub-screen) ──────────────────────
    "language.picker.title"         -> "Language",
    "language.picker.error"         -> "Couldn't load languages — tap Retry.",

    // ── Custom feed editor (Settings sub-screen) ───────────────────
    "customFeed.title"              -> "My custom feed",
    "customFeed.description"        -> "Describe the kind of news you want to see. We'll match articles to your description on every refresh.",
    "customFeed.placeholder"        -> "e.g. Dutch housing market",
    "customFeed.deleteConfirm.title"-> "Delete your custom feed?",
    "customFeed.deleteConfirm.message" -> "The feed will switch back to the default trending mix.",
    "customFeed.saveError"          -> "Could not save your custom feed. Try again later.",

    // ── Home screen ────────────────────────────────────────────────
    "home.tab.trending"             -> "Trending",
    "home.empty.titleFormat"        -> "No articles in %@ yet",
    "home.empty.subtitle"           -> "Try another category or check back later.",
    "home.empty.showAll"            -> "Show All News",
    "home.banner.categoriesEmpty"   -> "No news in your preferred categories — showing all news",
    "home.banner.semanticUnavailable" -> "Search is down right now — showing all news",
    "home.banner.semanticNoMatch"   -> "No news for your query — showing all news",
    "home.sentinel.title"           -> "You're all caught up",
    "home.sentinel.subtitle"        -> "Showing you the older news now.",
    "home.menu.categories"          -> "Categories",
    "home.menu.settings"            -> "Settings",

    // ── Search ─────────────────────────────────────────────────────
    "search.title"                  -> "Search News",
    "search.placeholder"            -> "Search news",

    // ── Detail ─────────────────────────────────────────────────────
    "detail.invalidUrl"             -> "Invalid URL",
    "detail.noDescription"          -> "No description available",

    // ── Location / country picker ──────────────────────────────────
    "country.picker.title"          -> "Country",

    // ── Error alerts ───────────────────────────────────────────────
    "alert.serverError.title"       -> "Server Error",
    "alert.serverError.invalidData" -> "The data received from the server was invalid. Please contact support",
    "alert.serverError.invalidResponse" -> "Invalid response from server. Please try again later or contact support",
    "alert.serverError.invalidUrl"  -> "There was an issue connecting to the server. Please contact support",
    "alert.serverError.noInternet"  -> "Make sure you are connected to internet",
    "alert.form.incomplete"         -> "Please ensure all fields in the form have been filled out.",
    "alert.form.invalidEmail"       -> "Please ensure your email is correct.",
    "alert.deleteAccount.failed"    -> "Couldn't Delete Account",
  )

  /** Dutch — full coverage. Other 5 locales seeded best-effort below;
    * the iOS / Android clients fall back to the English row at lookup
    * time for any missing key, so partial coverage is acceptable.
    */
  private val nl: Map[String, String] = Map(
    "common.continue"               -> "Doorgaan",
    "common.cancel"                 -> "Annuleren",
    "common.skip"                   -> "Overslaan",
    "common.retry"                  -> "Opnieuw proberen",
    "common.save"                   -> "Opslaan",
    "common.edit"                   -> "Bewerken",
    "common.delete"                 -> "Verwijderen",
    "common.ok"                     -> "OK",
    "common.close"                  -> "Sluiten",

    "app.name"                      -> "Snel Nieuws",

    "forceUpdate.title"             -> "Update vereist",
    "forceUpdate.message"           -> "Er is een nieuwere versie van Snel Nieuws beschikbaar. Werk de app bij om door te gaan.",
    "forceUpdate.cta"               -> "Nu bijwerken",

    "login.greeting"                -> "Hey,\nwelkom bij",
    "login.email.title"             -> "E-mailadres",
    "login.email.placeholder"       -> "xyz@gmail.com",
    "login.password.title"          -> "Wachtwoord",
    "login.password.placeholder"    -> "*****",
    "login.forgotPassword"          -> "Wachtwoord vergeten?",
    "login.signUp"                  -> "REGISTREREN",
    "login.login"                   -> "INLOGGEN",
    "login.haveAccount"             -> "Heb je al een account?",
    "login.noAccount"               -> "Nog geen account?",
    "login.signUpCta"               -> "Registreren",
    "login.loginCta"                -> "Inloggen",
    "login.or"                      -> "OF",
    "login.google.cta"              -> "Doorgaan met Google",
    "login.privacy"                 -> "Door door te gaan, ga je akkoord met ons [Privacybeleid](https://api.snel.emudoi.com/privacy).",

    "onboarding.lang.title"         -> "Kies je taal",
    "onboarding.lang.subtitle"      -> "We tonen nieuws in deze taal. Je kunt dit altijd wijzigen in Instellingen.",
    "onboarding.lang.error"         -> "Talen konden niet worden geladen — probeer opnieuw.",

    "onboarding.notif.title"        -> "Blijf op de hoogte",
    "onboarding.notif.subtitle"     -> "Hoeveel updates wil je per dag ontvangen?",

    "onboarding.cat.title"          -> "Kies je onderwerpen",
    "onboarding.cat.subtitle"       -> "Kies de categorieën die je in je feed wilt zien. Je kunt dit altijd wijzigen via het menu.",
    "onboarding.cat.error"          -> "Categorieën konden niet worden geladen — probeer opnieuw.",
    "onboarding.cat.customFeed.title"      -> "Eigen feed (optioneel)",
    "onboarding.cat.customFeed.subtitle"   -> "Beschrijf welk nieuws je wilt zien en we matchen er artikelen aan.",
    "onboarding.cat.customFeed.placeholder"-> "bijv. Nederlandse woningmarkt",

    "settings.title"                -> "Instellingen",
    "settings.section.notifications"-> "MELDINGEN",
    "settings.section.categories"   -> "CATEGORIEËN",
    "settings.section.country"      -> "LAND",
    "settings.section.account"      -> "ACCOUNT",
    "settings.section.language"     -> "TAAL",
    "settings.section.customFeed"   -> "EIGEN FEED",

    "settings.language.label"       -> "Taal",
    "settings.country.label"        -> "Land",
    "settings.notifications.updatesPerDay"        -> "Hoeveel updates per dag",
    "settings.notifications.disabled.title"       -> "Meldingen zijn uitgeschakeld",
    "settings.notifications.disabled.subtitle"    -> "Tik om systeeminstellingen te openen",
    "settings.customFeed.setLabel"  -> "Stel een eigen query in",
    "settings.customFeed.savedLabel"-> "Je eigen query",
    "settings.customFeed.tapToDescribe" -> "Tik om je feed te beschrijven",

    "settings.account.logout"               -> "Uitloggen",
    "settings.account.privacyPolicy"        -> "Privacybeleid",
    "settings.account.deleteAccount"        -> "Account verwijderen",
    "settings.account.deleteConfirm.title"  -> "Account verwijderen?",
    "settings.account.deleteConfirm.message"-> "Dit verwijdert permanent je account, opgeslagen artikelen en alle gegevens die we over je bewaren. Dit kan niet ongedaan worden gemaakt.",

    "language.picker.title"         -> "Taal",
    "language.picker.error"         -> "Talen konden niet worden geladen — tik op Opnieuw.",

    "customFeed.title"              -> "Mijn eigen feed",
    "customFeed.description"        -> "Beschrijf welk soort nieuws je wilt zien. We matchen er artikelen aan bij elke ververs.",
    "customFeed.placeholder"        -> "bijv. Nederlandse woningmarkt",
    "customFeed.deleteConfirm.title"-> "Je eigen feed verwijderen?",
    "customFeed.deleteConfirm.message" -> "De feed schakelt terug naar de standaard trending mix.",
    "customFeed.saveError"          -> "Kan je eigen feed niet opslaan. Probeer het later opnieuw.",

    "home.tab.trending"             -> "Trending",
    "home.empty.titleFormat"        -> "Nog geen artikelen in %@",
    "home.empty.subtitle"           -> "Probeer een andere categorie of kom later terug.",
    "home.empty.showAll"            -> "Toon al het nieuws",
    "home.banner.categoriesEmpty"   -> "Geen nieuws in je voorkeurscategorieën — we tonen al het nieuws",
    "home.banner.semanticUnavailable" -> "Zoeken is momenteel niet beschikbaar — we tonen al het nieuws",
    "home.banner.semanticNoMatch"   -> "Geen nieuws voor je query — we tonen al het nieuws",
    "home.sentinel.title"           -> "Je bent helemaal bij",
    "home.sentinel.subtitle"        -> "We tonen je nu het oudere nieuws.",
    "home.menu.categories"          -> "Categorieën",
    "home.menu.settings"            -> "Instellingen",

    "search.title"                  -> "Zoek nieuws",
    "search.placeholder"            -> "Zoek nieuws",

    "detail.invalidUrl"             -> "Ongeldige URL",
    "detail.noDescription"          -> "Geen beschrijving beschikbaar",

    "country.picker.title"          -> "Land",

    "alert.serverError.title"       -> "Serverfout",
    "alert.serverError.invalidData" -> "De ontvangen data van de server is ongeldig. Neem contact op met support",
    "alert.serverError.invalidResponse" -> "Ongeldig antwoord van de server. Probeer het later opnieuw of neem contact op met support",
    "alert.serverError.invalidUrl"  -> "Er was een probleem met het verbinden met de server. Neem contact op met support",
    "alert.serverError.noInternet"  -> "Zorg dat je verbonden bent met internet",
    "alert.form.incomplete"         -> "Vul alle velden in het formulier in.",
    "alert.form.invalidEmail"       -> "Zorg dat je e-mailadres correct is.",
    "alert.deleteAccount.failed"    -> "Account kon niet worden verwijderd",
  )

  /** German — full coverage. */
  private val de: Map[String, String] = Map(
    "common.continue"               -> "Weiter",
    "common.cancel"                 -> "Abbrechen",
    "common.skip"                   -> "Überspringen",
    "common.retry"                  -> "Erneut versuchen",
    "common.save"                   -> "Speichern",
    "common.edit"                   -> "Bearbeiten",
    "common.delete"                 -> "Löschen",
    "common.ok"                     -> "OK",
    "common.close"                  -> "Schließen",
    "app.name"                      -> "Snel Nieuws",
    "forceUpdate.title"             -> "Update erforderlich",
    "forceUpdate.message"           -> "Eine neuere Version von Snel Nieuws ist verfügbar. Bitte aktualisieren, um fortzufahren.",
    "forceUpdate.cta"               -> "Jetzt aktualisieren",
    "login.greeting"                -> "Hey,\nwillkommen bei",
    "login.email.title"             -> "E-Mail-Adresse",
    "login.email.placeholder"       -> "xyz@gmail.com",
    "login.password.title"          -> "Passwort",
    "login.password.placeholder"    -> "*****",
    "login.forgotPassword"          -> "Passwort vergessen?",
    "login.signUp"                  -> "REGISTRIEREN",
    "login.login"                   -> "ANMELDEN",
    "login.haveAccount"             -> "Hast du bereits ein Konto?",
    "login.noAccount"               -> "Noch kein Konto?",
    "login.signUpCta"               -> "Registrieren",
    "login.loginCta"                -> "Anmelden",
    "login.or"                      -> "ODER",
    "login.google.cta"              -> "Mit Google fortfahren",
    "login.privacy"                 -> "Indem du fortfährst, stimmst du unserer [Datenschutzrichtlinie](https://api.snel.emudoi.com/privacy) zu.",
    "onboarding.lang.title"         -> "Wähle deine Sprache",
    "onboarding.lang.subtitle"      -> "Wir zeigen Nachrichten in dieser Sprache. Du kannst sie jederzeit in den Einstellungen ändern.",
    "onboarding.lang.error"         -> "Sprachen konnten nicht geladen werden — bitte erneut versuchen.",
    "onboarding.notif.title"        -> "Bleib auf dem Laufenden",
    "onboarding.notif.subtitle"     -> "Wie viele Nachrichten-Updates möchtest du pro Tag erhalten?",
    "onboarding.cat.title"          -> "Wähle deine Themen",
    "onboarding.cat.subtitle"       -> "Wähle die Kategorien, die du in deinem Feed sehen möchtest. Du kannst dies jederzeit über das Menü ändern.",
    "onboarding.cat.error"          -> "Kategorien konnten nicht geladen werden — bitte erneut versuchen.",
    "onboarding.cat.customFeed.title"      -> "Eigener Feed (optional)",
    "onboarding.cat.customFeed.subtitle"   -> "Beschreibe die Art von Nachrichten, die du sehen möchtest, und wir passen Artikel daran an.",
    "onboarding.cat.customFeed.placeholder"-> "z.B. Deutscher Wohnungsmarkt",
    "settings.title"                -> "Einstellungen",
    "settings.section.notifications"-> "BENACHRICHTIGUNGEN",
    "settings.section.categories"   -> "KATEGORIEN",
    "settings.section.country"      -> "LAND",
    "settings.section.account"      -> "KONTO",
    "settings.section.language"     -> "SPRACHE",
    "settings.section.customFeed"   -> "MEIN EIGENER FEED",
    "settings.language.label"       -> "Sprache",
    "settings.country.label"        -> "Land",
    "settings.notifications.updatesPerDay"        -> "Wie viele Updates pro Tag",
    "settings.notifications.disabled.title"       -> "Benachrichtigungen sind deaktiviert",
    "settings.notifications.disabled.subtitle"    -> "Tippen, um Systemeinstellungen zu öffnen",
    "settings.customFeed.setLabel"  -> "Eigene Suche einrichten",
    "settings.customFeed.savedLabel"-> "Deine eigene Suche",
    "settings.customFeed.tapToDescribe" -> "Tippen, um deinen Feed zu beschreiben",
    "settings.account.logout"               -> "Abmelden",
    "settings.account.privacyPolicy"        -> "Datenschutzrichtlinie",
    "settings.account.deleteAccount"        -> "Konto löschen",
    "settings.account.deleteConfirm.title"  -> "Konto löschen?",
    "settings.account.deleteConfirm.message"-> "Dies entfernt dauerhaft dein Konto, gespeicherte Artikel und alle Daten, die wir über dich speichern. Dies kann nicht rückgängig gemacht werden.",
    "language.picker.title"         -> "Sprache",
    "language.picker.error"         -> "Sprachen konnten nicht geladen werden — tippe auf Erneut versuchen.",
    "customFeed.title"              -> "Mein eigener Feed",
    "customFeed.description"        -> "Beschreibe die Art von Nachrichten, die du sehen möchtest. Wir passen Artikel bei jeder Aktualisierung an deine Beschreibung an.",
    "customFeed.placeholder"        -> "z.B. Deutscher Wohnungsmarkt",
    "customFeed.deleteConfirm.title"-> "Eigenen Feed löschen?",
    "customFeed.deleteConfirm.message" -> "Der Feed wechselt zurück zum Standard-Trending-Mix.",
    "customFeed.saveError"          -> "Eigener Feed konnte nicht gespeichert werden. Bitte später erneut versuchen.",
    "home.tab.trending"             -> "Trending",
    "home.empty.titleFormat"        -> "Noch keine Artikel in %@",
    "home.empty.subtitle"           -> "Versuche eine andere Kategorie oder schau später wieder vorbei.",
    "home.empty.showAll"            -> "Alle Nachrichten anzeigen",
    "home.banner.categoriesEmpty"   -> "Keine Nachrichten in deinen bevorzugten Kategorien — alle Nachrichten anzeigen",
    "home.banner.semanticUnavailable" -> "Die Suche ist gerade nicht verfügbar — alle Nachrichten anzeigen",
    "home.banner.semanticNoMatch"   -> "Keine Nachrichten zu deiner Suche — alle Nachrichten anzeigen",
    "home.sentinel.title"           -> "Du bist auf dem neuesten Stand",
    "home.sentinel.subtitle"        -> "Wir zeigen dir jetzt die älteren Nachrichten.",
    "home.menu.categories"          -> "Kategorien",
    "home.menu.settings"            -> "Einstellungen",
    "search.title"                  -> "Nachrichten suchen",
    "search.placeholder"            -> "Nachrichten suchen",
    "detail.invalidUrl"             -> "Ungültige URL",
    "detail.noDescription"          -> "Keine Beschreibung verfügbar",
    "country.picker.title"          -> "Land",
    "alert.serverError.title"       -> "Serverfehler",
    "alert.serverError.invalidData" -> "Die vom Server empfangenen Daten waren ungültig. Bitte kontaktiere den Support",
    "alert.serverError.invalidResponse" -> "Ungültige Antwort vom Server. Bitte versuche es später erneut oder kontaktiere den Support",
    "alert.serverError.invalidUrl"  -> "Es gab ein Problem beim Verbinden mit dem Server. Bitte kontaktiere den Support",
    "alert.serverError.noInternet"  -> "Stelle sicher, dass du mit dem Internet verbunden bist",
    "alert.form.incomplete"         -> "Bitte stelle sicher, dass alle Felder im Formular ausgefüllt sind.",
    "alert.form.invalidEmail"       -> "Bitte stelle sicher, dass deine E-Mail-Adresse korrekt ist.",
    "alert.deleteAccount.failed"    -> "Konto konnte nicht gelöscht werden",
  )

  /** French — full coverage. */
  private val fr: Map[String, String] = Map(
    "common.continue"               -> "Continuer",
    "common.cancel"                 -> "Annuler",
    "common.skip"                   -> "Passer",
    "common.retry"                  -> "Réessayer",
    "common.save"                   -> "Enregistrer",
    "common.edit"                   -> "Modifier",
    "common.delete"                 -> "Supprimer",
    "common.ok"                     -> "OK",
    "common.close"                  -> "Fermer",
    "app.name"                      -> "Snel Nieuws",
    "forceUpdate.title"             -> "Mise à jour requise",
    "forceUpdate.message"           -> "Une version plus récente de Snel Nieuws est disponible. Veuillez mettre à jour pour continuer.",
    "forceUpdate.cta"               -> "Mettre à jour",
    "login.greeting"                -> "Salut,\nbienvenue sur",
    "login.email.title"             -> "Adresse e-mail",
    "login.email.placeholder"       -> "xyz@gmail.com",
    "login.password.title"          -> "Mot de passe",
    "login.password.placeholder"    -> "*****",
    "login.forgotPassword"          -> "Mot de passe oublié ?",
    "login.signUp"                  -> "S'INSCRIRE",
    "login.login"                   -> "CONNEXION",
    "login.haveAccount"             -> "Vous avez déjà un compte ?",
    "login.noAccount"               -> "Pas de compte ?",
    "login.signUpCta"               -> "S'inscrire",
    "login.loginCta"                -> "Se connecter",
    "login.or"                      -> "OU",
    "login.google.cta"              -> "Continuer avec Google",
    "login.privacy"                 -> "En continuant, vous acceptez notre [Politique de confidentialité](https://api.snel.emudoi.com/privacy).",
    "onboarding.lang.title"         -> "Choisissez votre langue",
    "onboarding.lang.subtitle"      -> "Nous afficherons les actualités dans cette langue. Vous pouvez la changer à tout moment dans les Paramètres.",
    "onboarding.lang.error"         -> "Impossible de charger les langues — veuillez réessayer.",
    "onboarding.notif.title"        -> "Restez informé",
    "onboarding.notif.subtitle"     -> "Combien de mises à jour souhaitez-vous recevoir par jour ?",
    "onboarding.cat.title"          -> "Choisissez vos sujets",
    "onboarding.cat.subtitle"       -> "Choisissez les catégories que vous souhaitez voir dans votre fil. Vous pouvez modifier cela à tout moment depuis le menu.",
    "onboarding.cat.error"          -> "Impossible de charger les catégories — veuillez réessayer.",
    "onboarding.cat.customFeed.title"      -> "Fil personnalisé (optionnel)",
    "onboarding.cat.customFeed.subtitle"   -> "Décrivez le type d'actualités que vous voulez voir et nous y correspondrons des articles.",
    "onboarding.cat.customFeed.placeholder"-> "ex. marché immobilier néerlandais",
    "settings.title"                -> "Paramètres",
    "settings.section.notifications"-> "NOTIFICATIONS",
    "settings.section.categories"   -> "CATÉGORIES",
    "settings.section.country"      -> "PAYS",
    "settings.section.account"      -> "COMPTE",
    "settings.section.language"     -> "LANGUE",
    "settings.section.customFeed"   -> "MON FIL PERSONNALISÉ",
    "settings.language.label"       -> "Langue",
    "settings.country.label"        -> "Pays",
    "settings.notifications.updatesPerDay"        -> "Combien de mises à jour par jour",
    "settings.notifications.disabled.title"       -> "Notifications désactivées",
    "settings.notifications.disabled.subtitle"    -> "Touchez pour ouvrir les paramètres système",
    "settings.customFeed.setLabel"  -> "Définir une requête personnalisée",
    "settings.customFeed.savedLabel"-> "Votre requête personnalisée",
    "settings.customFeed.tapToDescribe" -> "Touchez pour décrire votre fil",
    "settings.account.logout"               -> "Déconnexion",
    "settings.account.privacyPolicy"        -> "Politique de confidentialité",
    "settings.account.deleteAccount"        -> "Supprimer le compte",
    "settings.account.deleteConfirm.title"  -> "Supprimer votre compte ?",
    "settings.account.deleteConfirm.message"-> "Cela supprime définitivement votre compte, les articles enregistrés et toutes les données que nous détenons sur vous. Cette action est irréversible.",
    "language.picker.title"         -> "Langue",
    "language.picker.error"         -> "Impossible de charger les langues — touchez Réessayer.",
    "customFeed.title"              -> "Mon fil personnalisé",
    "customFeed.description"        -> "Décrivez le type d'actualités que vous voulez voir. Nous y correspondrons des articles à chaque actualisation.",
    "customFeed.placeholder"        -> "ex. marché immobilier néerlandais",
    "customFeed.deleteConfirm.title"-> "Supprimer votre fil personnalisé ?",
    "customFeed.deleteConfirm.message" -> "Le fil reviendra au mix tendance par défaut.",
    "customFeed.saveError"          -> "Impossible d'enregistrer votre fil personnalisé. Veuillez réessayer plus tard.",
    "home.tab.trending"             -> "Tendances",
    "home.empty.titleFormat"        -> "Pas encore d'articles dans %@",
    "home.empty.subtitle"           -> "Essayez une autre catégorie ou revenez plus tard.",
    "home.empty.showAll"            -> "Afficher toutes les actualités",
    "home.banner.categoriesEmpty"   -> "Pas d'actualités dans vos catégories préférées — affichage de toutes les actualités",
    "home.banner.semanticUnavailable" -> "La recherche est indisponible — affichage de toutes les actualités",
    "home.banner.semanticNoMatch"   -> "Pas d'actualités pour votre requête — affichage de toutes les actualités",
    "home.sentinel.title"           -> "Vous êtes à jour",
    "home.sentinel.subtitle"        -> "Affichage des actualités plus anciennes maintenant.",
    "home.menu.categories"          -> "Catégories",
    "home.menu.settings"            -> "Paramètres",
    "search.title"                  -> "Rechercher",
    "search.placeholder"            -> "Rechercher des actualités",
    "detail.invalidUrl"             -> "URL invalide",
    "detail.noDescription"          -> "Aucune description disponible",
    "country.picker.title"          -> "Pays",
    "alert.serverError.title"       -> "Erreur serveur",
    "alert.serverError.invalidData" -> "Les données reçues du serveur étaient invalides. Veuillez contacter le support",
    "alert.serverError.invalidResponse" -> "Réponse invalide du serveur. Veuillez réessayer plus tard ou contacter le support",
    "alert.serverError.invalidUrl"  -> "Il y a eu un problème de connexion au serveur. Veuillez contacter le support",
    "alert.serverError.noInternet"  -> "Assurez-vous d'être connecté à Internet",
    "alert.form.incomplete"         -> "Veuillez vous assurer que tous les champs du formulaire sont remplis.",
    "alert.form.invalidEmail"       -> "Veuillez vous assurer que votre e-mail est correct.",
    "alert.deleteAccount.failed"    -> "Impossible de supprimer le compte",
  )

  /** Italian — full coverage. */
  private val it: Map[String, String] = Map(
    "common.continue"               -> "Continua",
    "common.cancel"                 -> "Annulla",
    "common.skip"                   -> "Salta",
    "common.retry"                  -> "Riprova",
    "common.save"                   -> "Salva",
    "common.edit"                   -> "Modifica",
    "common.delete"                 -> "Elimina",
    "common.ok"                     -> "OK",
    "common.close"                  -> "Chiudi",
    "app.name"                      -> "Snel Nieuws",
    "forceUpdate.title"             -> "Aggiornamento richiesto",
    "forceUpdate.message"           -> "È disponibile una versione più recente di Snel Nieuws. Aggiorna per continuare.",
    "forceUpdate.cta"               -> "Aggiorna ora",
    "login.greeting"                -> "Ciao,\nbenvenuto in",
    "login.email.title"             -> "Indirizzo email",
    "login.email.placeholder"       -> "xyz@gmail.com",
    "login.password.title"          -> "Password",
    "login.password.placeholder"    -> "*****",
    "login.forgotPassword"          -> "Password dimenticata?",
    "login.signUp"                  -> "REGISTRATI",
    "login.login"                   -> "ACCEDI",
    "login.haveAccount"             -> "Hai già un account?",
    "login.noAccount"               -> "Non hai un account?",
    "login.signUpCta"               -> "Registrati",
    "login.loginCta"                -> "Accedi",
    "login.or"                      -> "O",
    "login.google.cta"              -> "Continua con Google",
    "login.privacy"                 -> "Continuando, accetti la nostra [Informativa sulla privacy](https://api.snel.emudoi.com/privacy).",
    "onboarding.lang.title"         -> "Scegli la tua lingua",
    "onboarding.lang.subtitle"      -> "Mostreremo le notizie in questa lingua. Puoi cambiarla in qualsiasi momento nelle Impostazioni.",
    "onboarding.lang.error"         -> "Impossibile caricare le lingue — riprova.",
    "onboarding.notif.title"        -> "Resta aggiornato",
    "onboarding.notif.subtitle"     -> "Quanti aggiornamenti vuoi ricevere al giorno?",
    "onboarding.cat.title"          -> "Scegli i tuoi argomenti",
    "onboarding.cat.subtitle"       -> "Scegli le categorie che vuoi vedere nel tuo feed. Puoi cambiarle in qualsiasi momento dal menu.",
    "onboarding.cat.error"          -> "Impossibile caricare le categorie — riprova.",
    "onboarding.cat.customFeed.title"      -> "Feed personalizzato (opzionale)",
    "onboarding.cat.customFeed.subtitle"   -> "Descrivi il tipo di notizie che vuoi vedere e abbineremo gli articoli.",
    "onboarding.cat.customFeed.placeholder"-> "es. mercato immobiliare olandese",
    "settings.title"                -> "Impostazioni",
    "settings.section.notifications"-> "NOTIFICHE",
    "settings.section.categories"   -> "CATEGORIE",
    "settings.section.country"      -> "PAESE",
    "settings.section.account"      -> "ACCOUNT",
    "settings.section.language"     -> "LINGUA",
    "settings.section.customFeed"   -> "IL MIO FEED PERSONALIZZATO",
    "settings.language.label"       -> "Lingua",
    "settings.country.label"        -> "Paese",
    "settings.notifications.updatesPerDay"        -> "Quanti aggiornamenti al giorno",
    "settings.notifications.disabled.title"       -> "Notifiche disabilitate",
    "settings.notifications.disabled.subtitle"    -> "Tocca per aprire le impostazioni di sistema",
    "settings.customFeed.setLabel"  -> "Imposta una query personalizzata",
    "settings.customFeed.savedLabel"-> "La tua query personalizzata",
    "settings.customFeed.tapToDescribe" -> "Tocca per descrivere il tuo feed",
    "settings.account.logout"               -> "Esci",
    "settings.account.privacyPolicy"        -> "Informativa sulla privacy",
    "settings.account.deleteAccount"        -> "Elimina account",
    "settings.account.deleteConfirm.title"  -> "Eliminare il tuo account?",
    "settings.account.deleteConfirm.message"-> "Questo rimuove permanentemente il tuo account, gli articoli salvati e tutti i dati che conserviamo su di te. Questa azione non può essere annullata.",
    "language.picker.title"         -> "Lingua",
    "language.picker.error"         -> "Impossibile caricare le lingue — tocca Riprova.",
    "customFeed.title"              -> "Il mio feed personalizzato",
    "customFeed.description"        -> "Descrivi il tipo di notizie che vuoi vedere. Abbineremo gli articoli alla tua descrizione ad ogni aggiornamento.",
    "customFeed.placeholder"        -> "es. mercato immobiliare olandese",
    "customFeed.deleteConfirm.title"-> "Eliminare il tuo feed personalizzato?",
    "customFeed.deleteConfirm.message" -> "Il feed tornerà al mix di tendenze predefinito.",
    "customFeed.saveError"          -> "Impossibile salvare il tuo feed personalizzato. Riprova più tardi.",
    "home.tab.trending"             -> "Di tendenza",
    "home.empty.titleFormat"        -> "Nessun articolo in %@ ancora",
    "home.empty.subtitle"           -> "Prova un'altra categoria o ricontrolla più tardi.",
    "home.empty.showAll"            -> "Mostra tutte le notizie",
    "home.banner.categoriesEmpty"   -> "Nessuna notizia nelle tue categorie preferite — mostriamo tutte le notizie",
    "home.banner.semanticUnavailable" -> "La ricerca non è disponibile — mostriamo tutte le notizie",
    "home.banner.semanticNoMatch"   -> "Nessuna notizia per la tua query — mostriamo tutte le notizie",
    "home.sentinel.title"           -> "Sei aggiornato",
    "home.sentinel.subtitle"        -> "Ora ti mostriamo le notizie più vecchie.",
    "home.menu.categories"          -> "Categorie",
    "home.menu.settings"            -> "Impostazioni",
    "search.title"                  -> "Cerca notizie",
    "search.placeholder"            -> "Cerca notizie",
    "detail.invalidUrl"             -> "URL non valido",
    "detail.noDescription"          -> "Nessuna descrizione disponibile",
    "country.picker.title"          -> "Paese",
    "alert.serverError.title"       -> "Errore del server",
    "alert.serverError.invalidData" -> "I dati ricevuti dal server non erano validi. Contatta l'assistenza",
    "alert.serverError.invalidResponse" -> "Risposta non valida dal server. Riprova più tardi o contatta l'assistenza",
    "alert.serverError.invalidUrl"  -> "Si è verificato un problema durante la connessione al server. Contatta l'assistenza",
    "alert.serverError.noInternet"  -> "Assicurati di essere connesso a Internet",
    "alert.form.incomplete"         -> "Assicurati che tutti i campi del modulo siano compilati.",
    "alert.form.invalidEmail"       -> "Assicurati che la tua email sia corretta.",
    "alert.deleteAccount.failed"    -> "Impossibile eliminare l'account",
  )

  /** Spanish — full coverage. */
  private val es: Map[String, String] = Map(
    "common.continue"               -> "Continuar",
    "common.cancel"                 -> "Cancelar",
    "common.skip"                   -> "Omitir",
    "common.retry"                  -> "Reintentar",
    "common.save"                   -> "Guardar",
    "common.edit"                   -> "Editar",
    "common.delete"                 -> "Eliminar",
    "common.ok"                     -> "OK",
    "common.close"                  -> "Cerrar",
    "app.name"                      -> "Snel Nieuws",
    "forceUpdate.title"             -> "Actualización requerida",
    "forceUpdate.message"           -> "Hay una versión más reciente de Snel Nieuws disponible. Actualiza para continuar.",
    "forceUpdate.cta"               -> "Actualizar ahora",
    "login.greeting"                -> "Hola,\nbienvenido a",
    "login.email.title"             -> "Correo electrónico",
    "login.email.placeholder"       -> "xyz@gmail.com",
    "login.password.title"          -> "Contraseña",
    "login.password.placeholder"    -> "*****",
    "login.forgotPassword"          -> "¿Olvidaste tu contraseña?",
    "login.signUp"                  -> "REGISTRARSE",
    "login.login"                   -> "INICIAR SESIÓN",
    "login.haveAccount"             -> "¿Ya tienes una cuenta?",
    "login.noAccount"               -> "¿No tienes una cuenta?",
    "login.signUpCta"               -> "Registrarse",
    "login.loginCta"                -> "Iniciar sesión",
    "login.or"                      -> "O",
    "login.google.cta"              -> "Continuar con Google",
    "login.privacy"                 -> "Al continuar, aceptas nuestra [Política de privacidad](https://api.snel.emudoi.com/privacy).",
    "onboarding.lang.title"         -> "Elige tu idioma",
    "onboarding.lang.subtitle"      -> "Mostraremos las noticias en este idioma. Puedes cambiarlo en cualquier momento en Ajustes.",
    "onboarding.lang.error"         -> "No se pudieron cargar los idiomas — inténtalo de nuevo.",
    "onboarding.notif.title"        -> "Mantente al día",
    "onboarding.notif.subtitle"     -> "¿Cuántas actualizaciones quieres recibir al día?",
    "onboarding.cat.title"          -> "Elige tus temas",
    "onboarding.cat.subtitle"       -> "Elige las categorías que quieres ver en tu feed. Puedes cambiarlo en cualquier momento desde el menú.",
    "onboarding.cat.error"          -> "No se pudieron cargar las categorías — inténtalo de nuevo.",
    "onboarding.cat.customFeed.title"      -> "Feed personalizado (opcional)",
    "onboarding.cat.customFeed.subtitle"   -> "Describe el tipo de noticias que quieres ver y combinaremos artículos.",
    "onboarding.cat.customFeed.placeholder"-> "p. ej. mercado inmobiliario holandés",
    "settings.title"                -> "Ajustes",
    "settings.section.notifications"-> "NOTIFICACIONES",
    "settings.section.categories"   -> "CATEGORÍAS",
    "settings.section.country"      -> "PAÍS",
    "settings.section.account"      -> "CUENTA",
    "settings.section.language"     -> "IDIOMA",
    "settings.section.customFeed"   -> "MI FEED PERSONALIZADO",
    "settings.language.label"       -> "Idioma",
    "settings.country.label"        -> "País",
    "settings.notifications.updatesPerDay"        -> "Cuántas actualizaciones al día",
    "settings.notifications.disabled.title"       -> "Notificaciones desactivadas",
    "settings.notifications.disabled.subtitle"    -> "Toca para abrir los ajustes del sistema",
    "settings.customFeed.setLabel"  -> "Establece una consulta personalizada",
    "settings.customFeed.savedLabel"-> "Tu consulta personalizada",
    "settings.customFeed.tapToDescribe" -> "Toca para describir tu feed",
    "settings.account.logout"               -> "Cerrar sesión",
    "settings.account.privacyPolicy"        -> "Política de privacidad",
    "settings.account.deleteAccount"        -> "Eliminar cuenta",
    "settings.account.deleteConfirm.title"  -> "¿Eliminar tu cuenta?",
    "settings.account.deleteConfirm.message"-> "Esto elimina permanentemente tu cuenta, artículos guardados y todos los datos que tenemos sobre ti. Esto no se puede deshacer.",
    "language.picker.title"         -> "Idioma",
    "language.picker.error"         -> "No se pudieron cargar los idiomas — toca Reintentar.",
    "customFeed.title"              -> "Mi feed personalizado",
    "customFeed.description"        -> "Describe el tipo de noticias que quieres ver. Combinaremos artículos con tu descripción en cada actualización.",
    "customFeed.placeholder"        -> "p. ej. mercado inmobiliario holandés",
    "customFeed.deleteConfirm.title"-> "¿Eliminar tu feed personalizado?",
    "customFeed.deleteConfirm.message" -> "El feed volverá a la mezcla de tendencias predeterminada.",
    "customFeed.saveError"          -> "No se pudo guardar tu feed personalizado. Inténtalo más tarde.",
    "home.tab.trending"             -> "Tendencias",
    "home.empty.titleFormat"        -> "Aún no hay artículos en %@",
    "home.empty.subtitle"           -> "Prueba otra categoría o vuelve más tarde.",
    "home.empty.showAll"            -> "Mostrar todas las noticias",
    "home.banner.categoriesEmpty"   -> "Sin noticias en tus categorías preferidas — mostrando todas las noticias",
    "home.banner.semanticUnavailable" -> "La búsqueda no está disponible — mostrando todas las noticias",
    "home.banner.semanticNoMatch"   -> "Sin noticias para tu consulta — mostrando todas las noticias",
    "home.sentinel.title"           -> "Estás al día",
    "home.sentinel.subtitle"        -> "Ahora te mostramos las noticias más antiguas.",
    "home.menu.categories"          -> "Categorías",
    "home.menu.settings"            -> "Ajustes",
    "search.title"                  -> "Buscar noticias",
    "search.placeholder"            -> "Buscar noticias",
    "detail.invalidUrl"             -> "URL inválida",
    "detail.noDescription"          -> "Sin descripción disponible",
    "country.picker.title"          -> "País",
    "alert.serverError.title"       -> "Error del servidor",
    "alert.serverError.invalidData" -> "Los datos recibidos del servidor no eran válidos. Por favor, contacta con soporte",
    "alert.serverError.invalidResponse" -> "Respuesta no válida del servidor. Inténtalo más tarde o contacta con soporte",
    "alert.serverError.invalidUrl"  -> "Hubo un problema al conectar con el servidor. Por favor, contacta con soporte",
    "alert.serverError.noInternet"  -> "Asegúrate de estar conectado a internet",
    "alert.form.incomplete"         -> "Asegúrate de que todos los campos del formulario estén completos.",
    "alert.form.invalidEmail"       -> "Asegúrate de que tu correo electrónico sea correcto.",
    "alert.deleteAccount.failed"    -> "No se pudo eliminar la cuenta",
  )

  /** Polish — full coverage. */
  private val pl: Map[String, String] = Map(
    "common.continue"               -> "Kontynuuj",
    "common.cancel"                 -> "Anuluj",
    "common.skip"                   -> "Pomiń",
    "common.retry"                  -> "Spróbuj ponownie",
    "common.save"                   -> "Zapisz",
    "common.edit"                   -> "Edytuj",
    "common.delete"                 -> "Usuń",
    "common.ok"                     -> "OK",
    "common.close"                  -> "Zamknij",
    "app.name"                      -> "Snel Nieuws",
    "forceUpdate.title"             -> "Wymagana aktualizacja",
    "forceUpdate.message"           -> "Dostępna jest nowsza wersja Snel Nieuws. Zaktualizuj, aby kontynuować.",
    "forceUpdate.cta"               -> "Zaktualizuj teraz",
    "login.greeting"                -> "Cześć,\nwitaj w",
    "login.email.title"             -> "Adres e-mail",
    "login.email.placeholder"       -> "xyz@gmail.com",
    "login.password.title"          -> "Hasło",
    "login.password.placeholder"    -> "*****",
    "login.forgotPassword"          -> "Zapomniałeś hasła?",
    "login.signUp"                  -> "ZAREJESTRUJ SIĘ",
    "login.login"                   -> "ZALOGUJ SIĘ",
    "login.haveAccount"             -> "Masz już konto?",
    "login.noAccount"               -> "Nie masz konta?",
    "login.signUpCta"               -> "Zarejestruj się",
    "login.loginCta"                -> "Zaloguj się",
    "login.or"                      -> "LUB",
    "login.google.cta"              -> "Kontynuuj z Google",
    "login.privacy"                 -> "Kontynuując, akceptujesz naszą [Politykę prywatności](https://api.snel.emudoi.com/privacy).",
    "onboarding.lang.title"         -> "Wybierz swój język",
    "onboarding.lang.subtitle"      -> "Będziemy pokazywać wiadomości w tym języku. Możesz to zmienić w dowolnym momencie w Ustawieniach.",
    "onboarding.lang.error"         -> "Nie udało się załadować języków — spróbuj ponownie.",
    "onboarding.notif.title"        -> "Bądź na bieżąco",
    "onboarding.notif.subtitle"     -> "Ile aktualizacji wiadomości chcesz otrzymywać dziennie?",
    "onboarding.cat.title"          -> "Wybierz swoje tematy",
    "onboarding.cat.subtitle"       -> "Wybierz kategorie, które chcesz widzieć w swoim kanale. Możesz to zmienić w dowolnym momencie z menu.",
    "onboarding.cat.error"          -> "Nie udało się załadować kategorii — spróbuj ponownie.",
    "onboarding.cat.customFeed.title"      -> "Własny kanał (opcjonalnie)",
    "onboarding.cat.customFeed.subtitle"   -> "Opisz jakie wiadomości chcesz widzieć, a my dopasujemy artykuły.",
    "onboarding.cat.customFeed.placeholder"-> "np. holenderski rynek mieszkaniowy",
    "settings.title"                -> "Ustawienia",
    "settings.section.notifications"-> "POWIADOMIENIA",
    "settings.section.categories"   -> "KATEGORIE",
    "settings.section.country"      -> "KRAJ",
    "settings.section.account"      -> "KONTO",
    "settings.section.language"     -> "JĘZYK",
    "settings.section.customFeed"   -> "MÓJ WŁASNY KANAŁ",
    "settings.language.label"       -> "Język",
    "settings.country.label"        -> "Kraj",
    "settings.notifications.updatesPerDay"        -> "Ile aktualizacji dziennie",
    "settings.notifications.disabled.title"       -> "Powiadomienia są wyłączone",
    "settings.notifications.disabled.subtitle"    -> "Dotknij, aby otworzyć ustawienia systemu",
    "settings.customFeed.setLabel"  -> "Ustaw własne zapytanie",
    "settings.customFeed.savedLabel"-> "Twoje własne zapytanie",
    "settings.customFeed.tapToDescribe" -> "Dotknij, aby opisać swój kanał",
    "settings.account.logout"               -> "Wyloguj się",
    "settings.account.privacyPolicy"        -> "Polityka prywatności",
    "settings.account.deleteAccount"        -> "Usuń konto",
    "settings.account.deleteConfirm.title"  -> "Usunąć swoje konto?",
    "settings.account.deleteConfirm.message"-> "To trwale usuwa twoje konto, zapisane artykuły i wszystkie dane, które o tobie posiadamy. Tej czynności nie można cofnąć.",
    "language.picker.title"         -> "Język",
    "language.picker.error"         -> "Nie udało się załadować języków — dotknij Spróbuj ponownie.",
    "customFeed.title"              -> "Mój własny kanał",
    "customFeed.description"        -> "Opisz jakie wiadomości chcesz widzieć. Dopasujemy artykuły do twojego opisu przy każdym odświeżeniu.",
    "customFeed.placeholder"        -> "np. holenderski rynek mieszkaniowy",
    "customFeed.deleteConfirm.title"-> "Usunąć swój własny kanał?",
    "customFeed.deleteConfirm.message" -> "Kanał wróci do domyślnej mieszanki trendów.",
    "customFeed.saveError"          -> "Nie udało się zapisać twojego własnego kanału. Spróbuj ponownie później.",
    "home.tab.trending"             -> "Na czasie",
    "home.empty.titleFormat"        -> "Brak artykułów w %@",
    "home.empty.subtitle"           -> "Wypróbuj inną kategorię lub sprawdź ponownie później.",
    "home.empty.showAll"            -> "Pokaż wszystkie wiadomości",
    "home.banner.categoriesEmpty"   -> "Brak wiadomości w twoich preferowanych kategoriach — pokazujemy wszystkie wiadomości",
    "home.banner.semanticUnavailable" -> "Wyszukiwanie jest niedostępne — pokazujemy wszystkie wiadomości",
    "home.banner.semanticNoMatch"   -> "Brak wiadomości dla twojego zapytania — pokazujemy wszystkie wiadomości",
    "home.sentinel.title"           -> "Jesteś na bieżąco",
    "home.sentinel.subtitle"        -> "Pokazujemy ci teraz starsze wiadomości.",
    "home.menu.categories"          -> "Kategorie",
    "home.menu.settings"            -> "Ustawienia",
    "search.title"                  -> "Szukaj wiadomości",
    "search.placeholder"            -> "Szukaj wiadomości",
    "detail.invalidUrl"             -> "Nieprawidłowy URL",
    "detail.noDescription"          -> "Brak dostępnego opisu",
    "country.picker.title"          -> "Kraj",
    "alert.serverError.title"       -> "Błąd serwera",
    "alert.serverError.invalidData" -> "Dane otrzymane z serwera były nieprawidłowe. Skontaktuj się z pomocą techniczną",
    "alert.serverError.invalidResponse" -> "Nieprawidłowa odpowiedź z serwera. Spróbuj ponownie później lub skontaktuj się z pomocą techniczną",
    "alert.serverError.invalidUrl"  -> "Wystąpił problem z połączeniem z serwerem. Skontaktuj się z pomocą techniczną",
    "alert.serverError.noInternet"  -> "Upewnij się, że masz połączenie z internetem",
    "alert.form.incomplete"         -> "Upewnij się, że wszystkie pola w formularzu zostały wypełnione.",
    "alert.form.invalidEmail"       -> "Upewnij się, że twój e-mail jest poprawny.",
    "alert.deleteAccount.failed"    -> "Nie udało się usunąć konta",
  )

  val strings: Map[String, Map[String, String]] = Map(
    "en" -> en,
    "nl" -> nl,
    "de" -> de,
    "fr" -> fr,
    "it" -> it,
    "es" -> es,
    "pl" -> pl
  )

  /** Resolve the i18n payload for a caller's locale. Unknown locales
    * fall back to the English row. Mirrors `CategoryNames.forLocale`
    * semantics. The client-side `L10n` helper does its own per-key
    * English fallback for any key the caller's locale row omits.
    */
  def forLocale(locale: String): Map[String, String] =
    strings.getOrElse(locale, en)
}
