server {
  port = 8080
  port = ${?PORT}
}

database {
  driver    = "org.postgresql.Driver"
  host      = "localhost"
  host      = ${?DB_HOST}
  port      = 5432
  port      = ${?DB_PORT}
  name      = "snelnieuws"
  name      = ${?DB_NAME}
  url       = "jdbc:postgresql://"${database.host}":"${database.port}"/"${database.name}
  url       = ${?DB_URL}
  user      = "postgres"
  user      = ${?DB_USER}
  password  = "postgres"
  password  = ${?DB_PASSWORD}
  pool-size = 10
}
