server {
  port = 8080
  port = ${?PORT}
}

database {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/snelnieuws"
  url = ${?DATABASE_URL}
  user = "postgres"
  user = ${?DATABASE_USER}
  password = "postgres"
  password = ${?DATABASE_PASSWORD}
  pool-size = 10
}
