INSERT INTO articles (author, title, description, url, url_to_image, content, category) VALUES
('John Smith', 'Breaking: Major Tech Company Announces Revolutionary AI Product', 'A leading technology company has unveiled its latest artificial intelligence product that promises to transform how we interact with computers.', 'https://example.com/tech-ai-product', 'https://picsum.photos/800/600?random=1', 'The tech industry was buzzing today as a major company announced its groundbreaking AI assistant. The new product uses advanced machine learning algorithms to understand and respond to human queries with unprecedented accuracy. Industry analysts predict this could be a game-changer for the sector.', 'Trending'),

('Sarah Johnson', 'Global Markets Rally on Positive Economic News', 'Stock markets around the world surge as new economic data suggests stronger than expected growth.', 'https://example.com/markets-rally', 'https://picsum.photos/800/600?random=2', 'Financial markets experienced significant gains today following the release of better-than-expected economic indicators. The S&P 500 rose by 2.3%, while European markets also posted strong gains. Economists point to improving consumer confidence and robust job numbers as key factors.', 'Business'),

('Dr. Emily Chen', 'New Study Reveals Benefits of Mediterranean Diet', 'Research shows significant health improvements for those following a Mediterranean-style eating pattern.', 'https://example.com/mediterranean-diet', 'https://picsum.photos/800/600?random=3', 'A comprehensive new study published in the Journal of Nutrition has found that following a Mediterranean diet can reduce the risk of heart disease by up to 30%. The research followed 10,000 participants over five years and tracked various health markers.', 'Health'),

('Michael Torres', 'Championship Finals Set After Dramatic Semifinal Matches', 'Two powerhouse teams advance to the finals after nail-biting semifinal victories.', 'https://example.com/sports-finals', 'https://picsum.photos/800/600?random=4', 'In what many are calling the most exciting semifinals in recent memory, both matches went to overtime before the winning teams finally emerged. The championship final is set for next weekend, with millions of fans expected to tune in worldwide.', 'Sports'),

('Lisa Wang', 'Climate Summit Reaches Historic Agreement', 'World leaders agree on ambitious new targets to combat climate change at the annual summit.', 'https://example.com/climate-summit', 'https://picsum.photos/800/600?random=5', 'After intense negotiations lasting through the night, delegates from over 190 countries have agreed to a landmark climate deal. The agreement includes commitments to reduce carbon emissions by 50% by 2035 and achieve net-zero emissions by 2050.', 'Trending'),

('Robert Kim', 'Startup Raises $100M for Sustainable Energy Solutions', 'Green tech company secures major funding to expand its renewable energy technology.', 'https://example.com/startup-funding', 'https://picsum.photos/800/600?random=6', 'A promising startup focused on sustainable energy solutions has closed a $100 million Series C funding round. The company plans to use the investment to scale production of its innovative solar panel technology that is 40% more efficient than current market offerings.', 'Business'),

('Dr. Amanda Foster', 'Breakthrough in Cancer Research Shows Promising Results', 'Scientists announce significant progress in developing new cancer treatment approach.', 'https://example.com/cancer-research', 'https://picsum.photos/800/600?random=7', 'Researchers at a leading medical institution have announced a breakthrough in cancer treatment. The new therapy, which harnesses the body own immune system, has shown remarkable success in early clinical trials, with 80% of patients experiencing tumor reduction.', 'Health'),

('James Wilson', 'Star Athlete Breaks World Record in Stunning Performance', 'Record-breaking achievement stuns spectators at international competition.', 'https://example.com/world-record', 'https://picsum.photos/800/600?random=8', 'In an awe-inspiring display of athletic prowess, a star athlete shattered the long-standing world record during today competition. The new record, which had stood for over a decade, was broken by a margin that left commentators and fans alike in disbelief.', 'Sports'),

('Nina Patel', 'New Smartphone Features Revolutionary Camera Technology', 'Latest flagship device promises to transform mobile photography with cutting-edge sensors.', 'https://example.com/smartphone-camera', 'https://picsum.photos/800/600?random=9', 'The newest flagship smartphone from a leading manufacturer features camera technology that rivals professional equipment. With a 200MP sensor, advanced AI processing, and revolutionary low-light capabilities, mobile photography is entering a new era.', 'Trending'),

('Dr. Mark Stevens', 'Study Links Sleep Quality to Mental Health Improvements', 'Research demonstrates strong correlation between better sleep and reduced anxiety.', 'https://example.com/sleep-study', 'https://picsum.photos/800/600?random=10', 'A new study involving over 5,000 participants has found that improving sleep quality can significantly reduce symptoms of anxiety and depression. Researchers recommend establishing consistent sleep schedules and limiting screen time before bed for optimal mental health benefits.', 'Health'),

('Alexandra Brown', 'Major League Announces Expansion to New Markets', 'Sports league reveals plans to add teams in three new cities over the next five years.', 'https://example.com/league-expansion', 'https://picsum.photos/800/600?random=11', 'In a major announcement, the league commissioner revealed ambitious expansion plans that will bring professional sports to three new markets. The move is expected to generate billions in economic activity and create thousands of jobs in the selected cities.', 'Sports'),

('David Chen', 'E-Commerce Giant Reports Record Holiday Sales', 'Online retailer breaks previous records with unprecedented holiday shopping season.', 'https://example.com/ecommerce-sales', 'https://picsum.photos/800/600?random=12', 'The latest earnings report from a major e-commerce company shows record-breaking holiday sales, with revenue up 35% compared to last year. The company attributes the success to improved logistics, expanded product selection, and enhanced mobile shopping experience.', 'Business');
